version: '3.7'

services:
  web:
    build: .
    command: daphne -b 127.0.0.1 -p 8000 simple_im.asgi:application
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: erp_db_base
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:  