version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=main_user
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=erp_database
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: